import json, os

FILE = r"c:\Users\amine\OneDrive\Desktop\Moroverse\frontend\data\generated-content.json"

with open(FILE, encoding='utf-8') as f:
    db = json.load(f)

db['battles'] = [
  {"id":"wadi-lakka-711","name":{"en":"Battle of Guadalete","ar":"معركة وادي لكة"},"era":"العصر الأموي","year":"711","desc":{"en":"The decisive battle where Tariq ibn Ziyad led Islamic forces to victory over the Visigoths, opening Iberia to Islam.","ar":"المعركة الفاصلة التي قاد فيها طارق بن زياد القوات الإسلامية وفتح الأندلس."},"leaders":{"en":"Tariq ibn Ziyad","ar":"طارق بن زياد"},"combatants":{"en":"Umayyad Forces vs. Visigoths","ar":"قوات أموية ضد القوط الغربيين"},"outcome":{"en":"Islamic Victory — Fall of Visigothic Kingdom","ar":"انتصار إسلامي — سقوط مملكة القوط الغربيين"},"tactics":{"en":"Feigned retreat luring the Visigoths into decisive encirclement.","ar":"التراجع الخادع لجذب القوط الغربيين نحو حصار حاسم."},"imageUrl":"https://images.unsplash.com/photo-1534759846116-5799c33ce22a?q=80&w=1080","isPending":False,"visualSoul":"Fortress"},
  {"id":"battle-of-nobles","name":{"en":"Battle of the Nobles","ar":"معركة الأشراف"},"era":"العصر الأموي","year":"740","desc":{"en":"A defining Berber uprising against Umayyad rule that changed the political landscape of North Africa.","ar":"انتفاضة أمازيغية حاسمة ضد الحكم الأموي غيّرت المشهد السياسي في شمال أفريقيا."},"leaders":{"en":"Maysara al-Matghari","ar":"ميسرة المطغري"},"combatants":{"en":"Berber League vs. Umayyad Caliphate","ar":"أمازيغ ضد الخلافة الأموية"},"outcome":{"en":"Berber Victory","ar":"نصر أمازيغي"},"imageUrl":"https://images.unsplash.com/photo-1502920917128-1aa500764cbd?q=80&w=1080","isPending":False,"visualSoul":"Ruin"},
  {"id":"zallaqah-1086","name":{"en":"Battle of Zallaqa","ar":"معركة الزلاقة"},"era":"العصر المرابطي","year":"1086","desc":{"en":"One of the greatest medieval victories — Yusuf ibn Tashfin crushed Alfonso VI, halting the Reconquista.","ar":"من أعظم انتصارات العصور الوسطى — يوسف بن تاشفين يسحق ألفونسو السادس."},"leaders":{"en":"Yusuf ibn Tashfin","ar":"يوسف بن تاشفين"},"combatants":{"en":"Almoravid Empire + Andalusian Taifas vs. Kingdom of Castile","ar":"المرابطون وإمارات الأندلس ضد مملكة قشتالة"},"outcome":{"en":"Decisive Muslim Victory","ar":"انتصار مسلم ساحق"},"tactics":{"en":"Tactical encirclement with war drums creating psychological pressure.","ar":"الإحاطة التكتيكية مع طبول الحرب لخلق ضغط نفسي."},"imageUrl":"https://images.unsplash.com/photo-1524820197278-540935d08664?q=80&w=1080","isPending":False,"visualSoul":"Fortress"},
  {"id":"alarcos-1195","name":{"en":"Battle of Alarcos","ar":"معركة الأرك"},"era":"العصر الموحدي","year":"1195","desc":{"en":"Sultan Al-Mansur annihilates Alfonso VIII of Castile, reclaiming al-Andalus northern frontier.","ar":"السلطان يعقوب المنصور يسحق ألفونسو الثامن ويستعيد الحدود الشمالية للأندلس."},"leaders":{"en":"Yaqub al-Mansur","ar":"يعقوب المنصور الموحدي"},"combatants":{"en":"Almohad Caliphate vs. Kingdom of Castile","ar":"الخلافة الموحدية ضد مملكة قشتالة"},"outcome":{"en":"Major Almohad Victory","ar":"انتصار موحدي كبير"},"imageUrl":"https://images.unsplash.com/photo-1560979169-3aaebf8e1aeed?q=80&w=1080","isPending":False,"visualSoul":"Fortress"},
  {"id":"las-navas-1212","name":{"en":"Battle of Las Navas de Tolosa","ar":"معركة العقاب"},"era":"العصر الموحدي","year":"1212","desc":{"en":"The pivotal battle that began the decline of the Almohad Caliphate in Iberia.","ar":"المعركة الفارقة التي مثّلت بداية تراجع الخلافة الموحدية."},"leaders":{"en":"Muhammad al-Nasir (Almohad)","ar":"محمد الناصر الموحدي"},"combatants":{"en":"Almohad Caliphate vs. Christian Coalition","ar":"الموحدون ضد التحالف المسيحي"},"outcome":{"en":"Christian Victory — Almohad retreat begins","ar":"نصر التحالف المسيحي — بداية تراجع الموحدين"},"imageUrl":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1080","isPending":False,"visualSoul":"Ruin"},
  {"id":"wadi-almakhazin-1578","name":{"en":"Battle of Alcácer Quibir (Three Kings)","ar":"معركة وادي المخازن — معركة الملوك الثلاثة"},"era":"العصر السعدي الذهبي","year":"1578","desc":{"en":"Morocco defeats Portugal and three kings die on the same day — one of history's greatest upsets.","ar":"المغرب يهزم البرتغال ويموت ثلاثة ملوك في نفس اليوم."},"leaders":{"en":"Ahmad al-Mansur / Abu Marwan Abd al-Malik","ar":"أحمد المنصور الذهبي — أبو مروان عبد الملك"},"combatants":{"en":"Saadian Morocco vs. Kingdom of Portugal","ar":"المغرب السعدي ضد مملكة البرتغال"},"outcome":{"en":"Crushing Moroccan Victory","ar":"انتصار مغربي ساحق"},"tactics":{"en":"The dying sultan led the battle from his litter, concealing his death to maintain morale.","ar":"السلطان المحتضر قاد المعركة من محفته كاتماً أنفاسه."},"imageUrl":"https://images.unsplash.com/photo-1570537030879-32960ae36c1e?q=80&w=1080","isPending":False,"visualSoul":"Crown"},
  {"id":"isly-1844","name":{"en":"Battle of Isly","ar":"معركة إيسلي"},"era":"مقاومة الاستعمار","year":"1844","desc":{"en":"Morocco suffers a major defeat at the hands of the French army under Marshal Bugeaud following support for Algerian resistance.","ar":"المغرب يلقى هزيمة أمام الجيش الفرنسي إثر دعم المغرب لمقاومة الجزائر."},"leaders":{"en":"Sultan Abd al-Rahman II vs. Marshal Bugeaud","ar":"السلطان عبد الرحمن الثاني مقابل المارشال بوجو"},"combatants":{"en":"Moroccan Army vs. French Colonial Forces","ar":"الجيش المغربي ضد القوات الاستعمارية الفرنسية"},"outcome":{"en":"French Victory — Treaty of Lalla Maghnia","ar":"نصر فرنسي — معاهدة للة مغنية"},"imageUrl":"https://images.unsplash.com/photo-1478720568477-152d9b164e26?q=80&w=1080","isPending":False,"visualSoul":"Ruin"},
  {"id":"tetouan-1860","name":{"en":"Battle of Tetouan","ar":"حرب تطوان"},"era":"مقاومة الاستعمار","year":"1860","desc":{"en":"Spain declares war on Morocco and captures Tetouan after fierce resistance.","ar":"إسبانيا تعلن الحرب على المغرب وتحتل تطوان بعد مقاومة شرسة."},"leaders":{"en":"General O'Donnell (Spain)","ar":"الجنرال أودونيل"},"combatants":{"en":"Kingdom of Spain vs. Morocco","ar":"المملكة الإسبانية ضد المغرب"},"outcome":{"en":"Spanish Victory — Tetouan ceded briefly","ar":"نصر إسباني — تطوان تُفقد مؤقتاً"},"imageUrl":"https://images.unsplash.com/photo-1570537030879-32960ae36c1e?q=80&w=1080","isPending":False,"visualSoul":"Ruin"},
  {"id":"anwal-1921","name":{"en":"Battle of Anwal","ar":"معركة أنوال"},"era":"الجهاد الريفي","year":"1921","desc":{"en":"Abd el-Krim annihilates the Spanish Army — the greatest defeat of a colonial power by an indigenous force in history.","ar":"عبد الكريم الخطابي يسحق الجيش الإسباني — أكبر هزيمة لقوة استعمارية على يد مقاومة أهلية."},"leaders":{"en":"Abd el-Krim al-Khattabi","ar":"محمد بن عبد الكريم الخطابي"},"combatants":{"en":"Republic of the Rif vs. Spain","ar":"جمهورية الريف ضد إسبانيا"},"outcome":{"en":"Decisive Rif Victory. 8,000+ Spanish killed.","ar":"نصر ريفي ساحق. أكثر من 8,000 إسباني قتيل."},"tactics":{"en":"Guerrilla mountain warfare and superior terrain knowledge.","ar":"حرب العصابات الجبلية والتمكن الفائق من التضاريس."},"imageUrl":"https://images.unsplash.com/photo-1502920917128-1aa500764cbd?q=80&w=1080","isPending":False,"visualSoul":"Mountain"},
  {"id":"el-herri-1914","name":{"en":"Battle of El Herri","ar":"معركة الهري"},"era":"الجهاد الأمازيغي","year":"1914","desc":{"en":"Moha ou Hammou Zayani destroys a French column — a legendary Berber victory.","ar":"موحا أو حمو الزياني يدمر رتلاً فرنسياً — نصر أمازيغي أسطوري."},"leaders":{"en":"Moha ou Hammou Zayani","ar":"موحا أو حمو الزياني"},"combatants":{"en":"Zayane Confederation vs. French Colonial Forces","ar":"تحالف زيان ضد القوات الاستعمارية الفرنسية"},"outcome":{"en":"Moroccan Victory — French column destroyed","ar":"انتصار مغربي — الرتل الفرنسي مُدمَّر"},"imageUrl":"https://images.unsplash.com/photo-1560979169-3aaebf8e1aeed?q=80&w=1080","isPending":False,"visualSoul":"Mountain"},
  {"id":"bougafer-1933","name":{"en":"Battle of Bougafer","ar":"معركة بوغافر"},"era":"آخر المقاومة الجبلية","year":"1933","desc":{"en":"The last stand of Assou ou Bassalm and Ait Hadidou tribe — the last Berber resistance battle.","ar":"آخر موقف لعسو أوباسلام وقبيلة آيت حاديدو — آخر معارك المقاومة الأمازيغية."},"leaders":{"en":"Assou ou Bassalm","ar":"عسو أوباسلام"},"combatants":{"en":"Ait Hadidou Tribe vs. French & Spanish Forces","ar":"قبيلة آيت حاديدو ضد القوات الفرنسية والإسبانية"},"outcome":{"en":"Last Moroccan resistance collapses.","ar":"آخر مقاومة مغربية تنهار."},"imageUrl":"https://images.unsplash.com/photo-1534759846116-5799c33ce22a?q=80&w=1080","isPending":False,"visualSoul":"Mountain"}
]

db['figures'] = [
  {"id":"tariq-ibn-ziyad","name":{"en":"Tariq ibn Ziyad","ar":"طارق بن زياد"},"field":"القائد العسكري","era":"العصر الأموي","year":"711","desc":{"en":"Berber general who led the Islamic conquest of Hispania, crossing the strait that now bears his name — Gibraltar (Jabal Tariq).","ar":"القائد الأمازيغي الذي قاد فتح الأندلس وعبر المضيق الذي يحمل اسمه — جبل طارق."},"imageUrl":"https://images.unsplash.com/photo-1584291527935-96b5acd0a83e?q=80&w=1080","isPending":False},
  {"id":"yusuf-ibn-tashfin","name":{"en":"Yusuf ibn Tashfin","ar":"يوسف بن تاشفين"},"field":"السلطان المرابطي","era":"العصر المرابطي","year":"1086","desc":{"en":"Founder of Marrakech and Almoravid dynasty leader who saved al-Andalus at the Battle of Zallaqa.","ar":"مؤسس مدينة مراكش وقائد الدولة المرابطية الذي أنقذ الأندلس في معركة الزلاقة."},"imageUrl":"https://images.unsplash.com/photo-1570537030879-32960ae36c1e?q=80&w=1080","isPending":False},
  {"id":"yaqub-al-mansur","name":{"en":"Yaqub al-Mansur","ar":"يعقوب المنصور الموحدي"},"field":"السلطان الموحدي","era":"العصر الموحدي","year":"1195","desc":{"en":"Third Almohad Caliph who defeated Alfonso VIII at Alarcos, commissioned the Hassan Tower and Koutoubia Mosque.","ar":"ثالث خلفاء الموحدين الذي هزم ألفونسو الثامن وأمر ببناء صومعة حسان والكتبية."},"imageUrl":"https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=1080","isPending":False},
  {"id":"ahmad-al-mansur","name":{"en":"Ahmad al-Mansur al-Dhahabi","ar":"أحمد المنصور الذهبي"},"field":"السلطان السعدي","era":"العصر السعدي الذهبي","year":"1578","desc":{"en":"The golden sultan who defeated Portugal at the Battle of Three Kings, conquered the Songhay Empire and brought gold to Morocco.","ar":"السلطان الذهبي الذي هزم البرتغاليين وفتح مملكة سنغاي وجلب ذهب تمبكتو إلى المغرب."},"imageUrl":"https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=1080","isPending":False},
  {"id":"abd-el-krim","name":{"en":"Abd el-Krim al-Khattabi","ar":"عبد الكريم الخطابي"},"field":"قائد الجهاد الريفي","era":"الجهاد الريفي","year":"1921","desc":{"en":"Leader of the Rif Republic who inflicted the greatest colonial military defeat in history at Anwal.","ar":"زعيم جمهورية الريف الذي حقق أكبر هزيمة عسكرية استعمارية في التاريخ في معركة أنوال."},"imageUrl":"https://images.unsplash.com/photo-1524820197278-540935d08664?q=80&w=1080","isPending":False},
  {"id":"moha-ou-hammou","name":{"en":"Moha ou Hammou Zayani","ar":"موحا أو حمو الزياني"},"field":"شيخ المقاومة الأمازيغية","era":"الجهاد الأمازيغي","year":"1914","desc":{"en":"Iconic resistance hero who led the Zayane Confederation against French colonialism for two decades from the Atlas Mountains.","ar":"بطل المقاومة الذي قاد تحالف زيان ضد الاستعمار الفرنسي لعقدين من جبال الأطلس."},"imageUrl":"https://images.unsplash.com/photo-1502920917128-1aa500764cbd?q=80&w=1080","isPending":False},
  {"id":"ibn-battuta","name":{"en":"Ibn Battuta","ar":"ابن بطوطة"},"field":"الرحالة والجغرافي","era":"العصر المريني","year":"1330","desc":{"en":"The greatest medieval explorer who traveled 75,000 miles across the known world, born in Tangier.","ar":"أعظم رحّالة العصور الوسطى الذي قطع 120,000 كيلومتر عبر العالم، ولد في طنجة."},"imageUrl":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1080","isPending":False},
  {"id":"ibn-khaldun","name":{"en":"Ibn Khaldun","ar":"ابن خلدون"},"field":"الفيلسوف والمؤرخ","era":"العصر المريني","year":"1375","desc":{"en":"Father of sociology and historiography, Muqaddimah laid the foundation for modern social sciences.","ar":"أبو علم الاجتماع والتأريخ، مقدمته أرست أسس العلوم الاجتماعية الحديثة."},"imageUrl":"https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=1080","isPending":False}
]

if not db.get('tourism'):
    db['tourism'] = [
      {"id":"geotourism-anti-atlas","name":{"en":"Anti-Atlas Geotourism: Ancient Fossils","ar":"جيو-سياحة الأطلس الصغير: الحفريات القديمة"},"type":"Geotourism","desc":{"en":"Explore the Anti-Atlas mountains home to the oldest fossilized life on Earth — trilobites, ammonites dating 350 million years.","ar":"استكشف جبال الأطلس الصغير موطن أقدم أشكال الحياة المتحجرة على وجه الأرض."},"activities":["Fossil Hunting","Geological Walks","Desert Stargazing"],"best_time":"October to April","imageUrl":"https://images.unsplash.com/photo-1518791841217-8f162f1912da?q=80&w=1080","lat":29.64,"lng":-8.87,"isPending":False},
      {"id":"dark-tourism-memory","name":{"en":"Dark Tourism: Memory Sites of Morocco","ar":"السياحة المظلمة: مواقع الذاكرة الوطنية"},"type":"Dark Tourism","desc":{"en":"Visit the sites where Morocco's colonial and resistance history was written — memory sites, prisons, and battlefield memorials.","ar":"زيارة مواقع كتب فيها تاريخ المغرب الاستعماري ومقاومته."},"activities":["Historical Tours","Memorial Visits","Documentary Screenings"],"best_time":"Year-round","imageUrl":"https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=1080","lat":33.57,"lng":-7.61,"isPending":False},
      {"id":"ecotourism-khettara","name":{"en":"Eco-Systems: Khettara & Saharan Oases","ar":"الأنظمة البيئية: الخطارات والواحات الصحراوية"},"type":"Ecotourism","desc":{"en":"Discover Morocco's ancient underground water system (Khettara) that sustained entire civilizations in the Sahara for millennia.","ar":"اكتشف نظام الخطارات القديم الذي حافظ على حضارات كاملة في الصحراء لآلاف السنين."},"activities":["Khettara Exploration","Palm Grove Tours","Oasis Ecology Walks"],"best_time":"November to March","imageUrl":"https://images.unsplash.com/photo-1534759846116-5799c33ce22a?q=80&w=1080","lat":31.93,"lng":-4.43,"isPending":False}
    ]

with open(FILE, 'w', encoding='utf-8') as f:
    json.dump(db, f, ensure_ascii=False, indent=2)

print(f"SUCCESS: battles={len(db.get('battles',[]))}, figures={len(db.get('figures',[]))}, tourism={len(db.get('tourism',[]))}")
